weat

diff --git a/.github/workflows/schedule-jobs.yml b/.github/workflows/schedule-jobs.yml
--- a/.github/workflows/schedule-jobs.yml
+++ b/.github/workflows/schedule-jobs.yml
@@ -72,10 +72,10 @@ jobs:
           echo "git push exit code: $?"
           git remote -v
           git branch -a
-          git branch --track ${{ github.event.repository.default_branch }}
-          echo "git branch exit code: $?"
-          git remote -v
-          git branch -a
+          # git branch --track ${{ github.event.repository.default_branch }}
+          # echo "git branch exit code: $?"
+          # git remote -v
+          # git branch -a
           git branch --set-upstream-to https://github.com/${{ env.UPSTREAM_REPO }}/${{ env.UPSTREAM_BRANCH }} ${{ github.event.repository.default_branch }}
           # git branch --set-upstream-to ${{ env.THIS_REMOTE }}/${{ github.event.repository.default_branch }}
           echo "git branch exit code: $?"
